DECLARE @StartDate DATE, @EndDate DATE
SET @StartDate = '20200101'
SET @EndDate = '20301231';

WITH CTE (thedatekey) AS ( SELECT 1 UNION SELECT 2 )

SELECT TOP (ABS ( DATEDIFF(day , @EndDate ,  @StartDate)) +1 )
		CAST( DATEADD( day , ROW_NUMBER() OVER (ORDER BY (SELECT 1) ) -1 , @StartDate) as Date) as DateKey ,
		YEAR(DATEADD( day , ROW_NUMBER() OVER (ORDER BY (SELECT 1) ) -1 , @StartDate)) as YearDate,
		DATEPART( QUARTER , (DATEADD( day , ROW_NUMBER() OVER (ORDER BY (SELECT 1) ) -1 , @StartDate)) ) as QuarterDate,
		MONTH(DATEADD( day , ROW_NUMBER() OVER (ORDER BY (SELECT 1) ) -1 , @StartDate)) as MonthDate,
		DAY(DATEADD( day , ROW_NUMBER() OVER (ORDER BY (SELECT 1) ) -1 , @StartDate)) as DayDate
		FROM CTE c1 
		CROSS APPLY CTE c2 CROSS APPLY CTE c3
		CROSS APPLY CTE c4 CROSS APPLY CTE c5
		CROSS APPLY CTE c6 CROSS APPLY CTE c7	
		CROSS APPLY CTE c8 CROSS APPLY CTE c9
		CROSS APPLY CTE c10 CROSS APPLY CTE c11 
    CROSS APPLY CTE c12
